#include "EzTuner.h"

volatile float eztuner_chassis_turn_kp = EZTUNER_CHASSIS_TURN_KP;
volatile float eztuner_chassis_turn_ki = EZTUNER_CHASSIS_TURN_KI;
volatile float eztuner_chassis_turn_kd = EZTUNER_CHASSIS_TURN_KD;
volatile float eztuner_chassis_turn_max_wz_radps = EZTUNER_CHASSIS_TURN_MAX_WZ_RADPS;
volatile float eztuner_chassis_turn_integral_limit = EZTUNER_CHASSIS_TURN_INTEGRAL_LIMIT;

volatile float eztuner_chassis_speed_kp = EZTUNER_CHASSIS_SPEED_KP;
volatile float eztuner_chassis_speed_ki = EZTUNER_CHASSIS_SPEED_KI;
volatile float eztuner_chassis_speed_kd = EZTUNER_CHASSIS_SPEED_KD;
volatile float eztuner_chassis_speed_max_output_percent = EZTUNER_CHASSIS_SPEED_MAX_OUTPUT_PERCENT;
volatile float eztuner_chassis_speed_integral_limit = EZTUNER_CHASSIS_SPEED_INTEGRAL_LIMIT;
